language: node_js
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"

services:
  - xvfb

git:
  depth: 5
addons:
  firefox: "latest"
before_script:
  - export DISPLAY=:99.0
before_install:
  - npm i -g npm@latest
install:
  - npm ci
  - npm run build
script:
  - npm run lint
  - npm test
after_success: npm run coverage
